/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package io.k8ssandra.pulsarcdctestutil

import db1.{table1key, table1value}
import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner
import org.scalatestplus.mockito.MockitoSugar._
import org.slf4j.LoggerFactory

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFunSuite {
  val mockLogger = LoggerFactory.getLogger(classOf[AppSuite])

  val mockPulsarClients = mock[PulsarClients]
  val pulsarOrchestrator = PulsarOrchestrator(mockPulsarClients)

  val mockCassClients = mock[CassandraClients]
  val cassandraOrchestrator = CassandraOrchestrator(mockCassClients)
  val tester = DataTester(cassandraOrchestrator, pulsarOrchestrator, mockLogger)

  test("DataTester has the right expectedData.") {
      assert(tester.expectedData.size == 10)
  }

  test("DataTester.checkData() has the right behaviour.") {
    assert(tester.checkData(tester.expectedData).isRight) // Self is always the same.
    assert(tester.checkData(Set[(table1key, table1value)]()).isLeft) // Empty vs expected is always an error
  }
}
